### ISSUE TITLE
Again incorrect scientific formatting.

### ISSUE THREAD

**Issue by ksromanov** [informatikr/aeson-pretty#22]
Would you please revert #19 . The reason - scientific package has updated, now it formats everything like it was [proposed](https://github.com/basvandijk/scientific/blob/master/src/Data/Text/Lazy/Builder/Scientific.hs#L48):

```
     Generic ->
      doFmt (if e < 0 || e > 7 then Exponent else Fixed)
            (is,e)
```

Aeson 1.2.1, instead, [does not check for large numbers (with exponent higher than 7)](https://github.com/bos/aeson/blob/master/Data/Aeson/Text.hs#L96):

```
fromScientific :: Scientific -> Builder
fromScientific s = formatScientificBuilder format prec s
  where
    (format, prec)
      | base10Exponent s < 0 = (Generic, Nothing)
      | otherwise            = (Fixed,   Just 0)
```

So, currently we have output:
```
"intBillion" : 1000000000
```

If you do not want to output trailing `.0`, you need to make a special formatter:

```
prettyFormatter :: S.Scientific -> Builder
prettyFormatter n
    | S.isFloating n == True = formatScientificBuilder S.Generic Nothing n
    | otherwise =formatScientificBuilder S.Generic (Just 0) n -- output no digits after decimal point
```

This will output

```
"double0" : 0,
"doubleHalf" : 0.5,
"intTwo" : 2,
"intMillion" : 1000000
"intBillion" : 1.0e9
```

**Comment by informatikr** [comment]
Can you send a PR, please? Maybe @leftaroundabout can also comment, since it was his change originally.

Thanks!

**Comment by leftaroundabout** [comment]
So first let's be clear we're talking about the same behaviours. Correct me if I'm wrong;

1. Old behaviour of `scientific`:
   ```
   "intTwo" : 2.0,
   "intMillion" : 1000000.0
   "intBillion" : 1.0e9
    ```
2. Currect behaviour of `scientific`:
   ```
   "intTwo" : 2,
   "intMillion" : 1000000
   "intBillion" : 1.0e9
    ```
3. Manual `Aeson` handling, as per https://github.com/informatikr/aeson-pretty/pull/19:
   ```
   "intTwo" : 2,
   "intMillion" : 1000000
   "intBillion" : 1000000000
    ```

Option 3. continues to have a big advantage, namely compatibility with standard Haskell literals, since
```
Prelude> 1.0e9 :: Int

<interactive>:2:1:
    No instance for (Fractional Int) arising from the literal ‘1.0e9’
    In the expression: 1.0e9 :: Int
    In an equation for ‘it’: it = 1.0e9 :: Int
```

Now, I reckon the behaviour you want changed is actually this:
```
Prelude Data.Aeson.Encode.Pretty> encodePretty (1.4e+32 :: Double)
"140000000000000000000000000000000"
```

Hm, I agree that this is not really acceptable for a library called “pretty”. So I would second reverting #19 if it leads to behaviour 2., but not if it makes 1. the default again.

**Comment by ksromanov** [comment]
First - the initial issue is more like an invitation for discussion with both of you. So, before making a PR or two, it would be better to make everything absolutely clear.

1. @leftaroundabout - no the behavior of scientific has not changed. So current is just like 1.

2. It looks like we are all on the same page about both cutting trailing zeroes and switching to scientific behavior for numbers less than `1.0` and larger than `1.0E+7` (the actual value of exponent is not essential, one can take maximal exponent of typical `int`, which is `int32`).

Unfortunately, the current implementation of this particular feature in `aeson-pretty` + `aeson` + `scientific` violates both behaviors.

The main reason is the loss of type information in `Data.Aeson.Types.Value` - `Number` encodes both integers and floating point numbers. `Scientific` is designed to recover this information only approximately using `isFloating` or `isInteger`.

3. There are several different solutions to this:

    a. Make a PR to `aeson` to use `Exponential` format for large numbers. As a cutoff we can safely take `30` - the limits for `Data.Int`. Large numbers will have trailing zero.

    b. Make a PR here using current `Aeson` code, just adding a special case `base10Exponent s > 29 -> scientific formatting`. Or instead reverting #19 and adding a special switch for integers, which will use fixed.

**Comment by leftaroundabout** [comment]
Yes, it's a bit of a dilemma. Perhaps Aeson should really have included special handling for integer numbers right from the beginning. Hang on, turns out it did! Until aeson-0.7, [the `Number` values used `Data.Attoparsec.Number`](http://hackage.haskell.org/package/aeson-0.6.2.1/docs/Data-Aeson-Types.html), which makes [a clear distinction](http://hackage.haskell.org/package/attoparsec-0.10.4.0/docs/Data-Attoparsec-Number.html#t:Number) between integral and floating.

Then https://github.com/bos/aeson/commit/715931e2b1a54b1639813a63c46fddb2f1002d43 changed it to `Scientific`, and there we are now. There has been a bit of discussion on this already, more related to compatibility with other languages.
https://github.com/bos/aeson/issues/181

Maybe the _right_ thing would actually be introducing a dedicated constructor for small integers, to have a clear distinction again:
```
data Value = Object !Object
           | Array !Array
           | String !Text
           | Scientific !Scientific
           | Int !Int
           | Bool !Bool
           | Null
             deriving (Eq, Read, Show, Typeable, Data)
```
but that would be a breaking change to _lots_ of libraries. If have my doubts if it'll happen.

The alternative, as you say, is to use some heuristics just for aeson-pretty. Your suggestion `base10Exponent s > 29 -> scientific formatting` is certainly a safe option, though it would still be a bit weird if, say, Avogadro's constant would be rendered as `602214085700000000000000`. Another option would be to use integral notation _whenever it is safe **and shorter than scientific**_. Determinin this would be a bit of an overhead, but for `pretty` this could be appropriate.

**Comment by ksromanov** [comment]
1. If we limit ourselves to `encode`, almost nothing will be broken - only new warnings will be produced, which is dangerous only with `-Werror`. (See the comment, which I've added to your `aeson` issue)

2. Even with heuristics, we have a choice of 3 libraries to make a PR. ;-) For me `Scientific` looks pretty solid, so, let's wait for the response in [bos/aeson/issue#546](https://github.com/bos/aeson/issues/546).

If they do not respond within 10 days, I'll make a PR with heuristics (the representation of Avogadro's constant makes me nervous ;-) ) to `aeson-pretty`.

**Comment by ksromanov** [comment]
Added PR #23. Please review and comment. I chose 1e7 as a cutoff according to documentation "simple decimals for fractional values between 0.1 and 9,999,999, and scientific notation otherwise". It is not exactly the same, but similar.

**Comment by informatikr** [comment]
PR #23 is now on Hackage.  Thanks guys!
